### ISSUE TITLE
IsZero condition should be removed

### ISSUE THREAD

**Issue by Aboudjem** [erc7579/erc7579-implementation#31]
https://github.com/erc7579/erc7579-implementation/blob/c1a0fa69d08f7992bc4e910b4a108fb21fc10fae/src/core/ExecutionHelper.sol#L81

The `iszero` operation should be removed since it inversely affects the conditional logic. By omitting `iszero` the `success` flag will correctly reflect the outcome of the `call`

**Comment by kopy-kat** [comment]
thanks for spotting this! fixed by https://github.com/erc7579/erc7579-implementation/commit/338bf8af011aa1588b5e1b2a19d1d7ead33bf779
